pipeline {
  environment {
    DEPLOY = "${env.BRANCH_NAME == "main" || env.BRANCH_NAME == "develop" ? "true" : "false"}"
  }
  agent {
    kubernetes {
      label 'kubernetes'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: terraform
    image: hashicorp/terraform
    command:
      - cat
    tty: true
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
}
  }

 stages {
        
   stage('Terraform') {
      steps {
      container('docker') {
        //withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:'GitHub',
       // usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']])
       // {
        git url: "https://github.com/mysticrenji/flask-mysql-k3s.git",  branch: 'main'
        sh '''
        cd terraform
        
           '''
      //  }
      }
   }
 }
 }
}
