kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: flaskapp-service
  namespace: flask
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: flaskapi-service
              servicePort: 80
          # - path: /nginx
          #   backend:
          #     serviceName: nginx-service
          #     servicePort: 80
  tls:
  - # cert-manager will store the certificate and key in this secret
    secretName: secrettoken
    hosts:
    - {{ .Values.hostName }}
