apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
  name: flask
spec:
  type: LoadBalancer
  ports:
  - name: flaskapi
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi