---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-mysql-k3s
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flask
      sourceRef:
        kind: HelmRepository
        name: flask-mysql-k3s
    values:
      hostName: app.dev-iots.in
  install: {}
  interval: 5m0s
  releaseName: flask
  targetNamespace: default

