name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: flask-mysql-k3s:v1
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build . --tag $IMAGE_NAME
      - uses: docker/login-action@v1
      - name: Log into Github Container Registry
      -	uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} 
      - name: Push Image to GitHub CR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          docker push $IMAGE_ID

